services:
  - type: web
    name: student-management-system
    env: go
    plan: free
    buildCommand: go build -o app ./cmd/web
    startCommand: ./app
    envVars:
      - key: GOVERSION
        value: 1.24.6
