// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/stackninja.pro/goth/internals/models"

func Navbar(td *models.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"w-full\"><div class=\"container mx-auto flex items-center justify-between px-4 py-3 md:py-4 lg:px-8\"><!-- Brand --><a href=\"/\" class=\"text-2xl font-bold text-emerald-400 hover:text-emerald-300 transition-colors\">Student<span class=\"text-orange-400\">Mgmt</span></a><!-- Hamburger (Mobile only) --><button class=\"md:hidden text-gray-300 hover:text-white focus:outline-none\" aria-label=\"Toggle Menu\" onclick=\"document.getElementById('mobile-menu').classList.toggle('hidden')\"><svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-7 w-7\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg></button><!-- Desktop Menu --><div class=\"hidden md:flex space-x-8 text-sm font-medium\"><a href=\"/\" class=\"hover:text-emerald-400 transition-colors\">Home</a> <a href=\"/about\" class=\"hover:text-orange-400 transition-colors\">About</a> <a href=\"/logout\" class=\"hover:text-teal-400 transition-colors\">Logout</a></div></div><!-- Mobile Menu --><div id=\"mobile-menu\" class=\"md:hidden hidden bg-gray-900/95 border-t border-gray-800\"><div class=\"flex flex-col space-y-2 px-4 py-4 text-sm font-medium\"><a href=\"/\" class=\"hover:text-emerald-400 transition-colors\">Home</a> <a href=\"/about\" class=\"hover:text-emerald-400 transition-colors\">About</a> <a href=\"/logout\" class=\"hover:text-emerald-400 transition-colors\">Logout</a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
