// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/stackninja.pro/goth/internals/models"
)

func Navbar(td *models.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"bg-white border-gray-200 dark:bg-gray-900\"><div class=\"max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4\"><a href=\"/\" class=\"flex items-center space-x-3 rtl:space-x-reverse\"><span class=\"self-center text-2xl font-semibold whitespace-nowrap dark:text-white\">KiniMtP</span></a><div class=\"flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if td.Data["userSession"] == nil {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a href=\"/login\" class=\"text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:ring-blue-300 \r\n\t\t\t\t\t\tfont-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-500 dark:hover:bg-blue-600 \r\n\t\t\t\t\t\tfocus:outline-none dark:focus:ring-blue-800\">Login</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			user := td.Data["userSession"].(*models.User)
			if user.Avatar != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<img src=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var2 string
				templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(user.Avatar)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/navbar.templ`, Line: 23, Col: 28}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"w-10 h-10 rounded-full mr-4 border-2 border-gray-700\" alt=\"User avatar\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<img class=\"w-10 h-10 rounded-full\" src=\"/static/img/prayers.jpg\" alt=\"Default avatar\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " <a href=\"/logout\" class=\"flex items-center justify-center gap-2 w-full px-4 py-2 bg-red-600 hover:bg-red-500 text-white rounded-lg shadow-sm transition duration-200\"><i class=\"fas fa-sign-out-alt\"></i> <span>Logout</span></a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"items-center justify-between hidden w-full md:flex md:w-auto md:order-1\" id=\"navbar-user\"><ul class=\"flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg \r\n\t\t\t\t\tbg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 \r\n\t\t\t\t\tmd:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700\"><li><a href=\"/\" class=\"block py-2 px-3 text-white bg-blue-700 rounded-sm \r\n\t\t\t\t\t\tmd:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500\" aria-current=\"page\">Home</a></li><li><a href=\"/about\" class=\"block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 \r\n\t\t\t\t\t\tmd:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white \r\n\t\t\t\t\t\tmd:dark:hover:text-blue-500\">About</a></li><li><a href=\"/services\" class=\"block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 \r\n\t\t\t\t\t\tmd:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white \r\n\t\t\t\t\t\tmd:dark:hover:text-blue-500\">Services</a></li><li><a href=\"/pricing\" class=\"block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 \r\n\t\t\t\t\t\tmd:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white \r\n\t\t\t\t\t\tmd:dark:hover:text-blue-500\">Pricing</a></li><li><a href=\"/contact\" class=\"block py-2 px-3 text-gray-900 rounded-sm hover:bg-gray-100 \r\n\t\t\t\t\t\tmd:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white \r\n\t\t\t\t\t\tmd:dark:hover:text-blue-500\">Contact</a></li></ul></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
