// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/stackninja.pro/goth/internals/models"

func ProfileFormDetails(td *models.TemplateData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col md:flex-row gap-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ProfileInformation(td).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<!-- Quick Actions --><div class=\"w-full md:w-1/2\"><div class=\"bg-gray-800 shadow-lg rounded-xl overflow-hidden\"><!-- Card Header --><div class=\"bg-gray-700 px-4 py-3 font-semibold text-lg text-gray-100 border-b border-gray-600\">Quick Actions</div><!-- Card Body --><div class=\"p-4 space-y-3\"><a href=\"/\" class=\"flex items-center justify-center gap-2 w-full px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg shadow-sm transition duration-200\"><i class=\"fas fa-cog\"></i> <span>Dashboard</span></a> <a href=\"/profile/edit\" class=\"flex items-center justify-center gap-2 w-full px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg shadow-sm transition duration-200\"><i class=\"fas fa-edit\"></i> <span>Edit Profile</span></a> <a href=\"/settings\" class=\"flex items-center justify-center gap-2 w-full px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded-lg shadow-sm transition duration-200\"><i class=\"fas fa-cog\"></i> <span>Settings</span></a> <a href=\"/logout\" class=\"flex items-center justify-center gap-2 w-full px-4 py-2 bg-red-600 hover:bg-red-500 text-white rounded-lg shadow-sm transition duration-200\"><i class=\"fas fa-sign-out-alt\"></i> <span>Logout</span></a></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
